---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <cert name>
spec:
  secretName: pblivelab-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames: 
  - <dns hostname>
